### ISSUE TITLE
Additional Security Options

### ISSUE THREAD

**Issue by somejavadev** [madbomb122/Win10Script#10]
**Is your feature request related to a problem? Please describe.**   
A clear and concise description of what the problem is.   

Thanks for this project, there are a couple of options I would like to additionally be able to configure.

**Describe the solution you'd like**   

I would like to have control over the following windows options:

Enable the screensaver.
Set the screensaver wait time.
Prompt and set local account password
Prompt login with password after resume from screensaver

**Describe alternatives you've considered**   

**Additional context**   

Ideally this would help in locking down the PC.

**Comment by madbomb122** [comment]
Sorry about the late reply been busy

I can do these 2 options (and working on adding them atm)
Enable the screensaver.
Prompt login with password after resume from screensaver

This one "Set the screensaver wait time."  I wont be doing this because there is no GUI item that accepts just numbers so it requires a lot more to. But I may do this at some point

This one "Prompt and set local account password" is something i wont do since this doesn't really fit with the script

**Comment by madbomb122** [comment]
If you want i can add the  "Set the screensaver wait time." item but it would not be configured in the GUI but from in script itself (you would have to go in the script and set it or from the config file that is loaded)

**Comment by somejavadev** [comment]
@madbomb122 Thanks for the efforts, if you add those 2 it would be perfect. The "Set the screensaver wait time." would be fine if it was done in the config file only, I will most likely set it to the same value for all PC's.

**Comment by madbomb122** [comment]
@somejavadev i'll have this posted shortly

Note:
the screensaver wait time can be set with the variable ($Script:ScreenSaverWaitTime) at the end of the script or by adding/editing the config file 
"ScreenSaverWaitTime";"NC"
^change NC to a whole number in seconds

**Comment by madbomb122** [comment]
Item added to V3.7.2
let me know if you have any issues
